crds:
  enabled: true

grafana:
  adminPassword: "admin1234"
  grafana.ini:
    dashboards:
      min_refresh_interval: 5s
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.127.0.0.1.nip.io
    path: /
    pathType: Prefix
  sidecar:
    dashboards:
      searchNamespace: ALL

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
