apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: player-data-prod

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: opus-major-assignment
      app.kubernetes.io/environment: prod

resources:
  - ../../base

patches:
  - path: patches/patch-rollout-replicas.yaml
    target:
      kind: Rollout
      name: player-data-service
  - path: patches/patch-rollout-analysis-namespace.yaml
    target:
      kind: Rollout
      name: player-data-service
  - path: patches/patch-ingress-host.yaml
    target:
      kind: Ingress
      name: player-data-service
  - path: patches/patch-prometheusrule-namespace.yaml
    target:
      kind: PrometheusRule
      name: player-data-service

images:
  - name: ghcr.io/isoardimarius/player-data-service
    newName: ghcr.io/isoardimarius/player-data-service
    digest: sha256:0478911e39dda7ddfac0523a499c4b7ac9023dbce84280da4a630974a77c2c47
