apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-guardrails
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/IsoardiMarius/opus-major-assignment.git
    targetRevision: main
    path: infra/apps/platform/policy-guardrails
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
