apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: player-data-dev

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: opus-major-assignment
      app.kubernetes.io/environment: dev

resources:
  - ../../base
  - observability/prometheusrule-demo-cpu.yaml

patches:
  - path: patches/patch-rollout-replicas.yaml
    target:
      kind: Rollout
      name: player-data-service
  - path: patches/patch-rollout-analysis-namespace.yaml
    target:
      kind: Rollout
      name: player-data-service
  - path: patches/patch-ingress-host.yaml
    target:
      kind: Ingress
      name: player-data-service
  - path: patches/patch-prometheusrule-namespace.yaml
    target:
      kind: PrometheusRule
      name: player-data-service

images:
  - name: ghcr.io/isoardimarius/player-data-service
    newName: ghcr.io/isoardimarius/player-data-service
    digest: sha256:c8e0cf11307a59ac4479890749771b61d1cd35cbc908447959bc67a1916627f4
