apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - core/serviceaccount.yaml
  - core/rollout.yaml
  - core/service.yaml
  - core/ingress.yaml
  - core/pdb.yaml
  - security/networkpolicy.yaml
  - observability/analysistemplate-rollout.yaml
  - observability/prometheusrule.yaml
  - observability/grafana-dashboard-configmap.yaml
  - observability/servicemonitor.yaml
