apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: player-data-staging

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: opus-major-assignment
      app.kubernetes.io/environment: staging

resources:
  - ../../base

patches:
  - path: patches/patch-rollout-replicas.yaml
    target:
      kind: Rollout
      name: player-data-service
  - path: patches/patch-rollout-analysis-namespace.yaml
    target:
      kind: Rollout
      name: player-data-service
  - path: patches/patch-ingress-host.yaml
    target:
      kind: Ingress
      name: player-data-service
  - path: patches/patch-prometheusrule-namespace.yaml
    target:
      kind: PrometheusRule
      name: player-data-service

images:
  - name: ghcr.io/isoardimarius/player-data-service
    newName: ghcr.io/isoardimarius/player-data-service
    digest: sha256:240e304dd7eb9e5f7c40b58c1fdd7069b096f6508fdd9aa88193cdeff95085a4
